# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
