# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhou', '0002_auto_20171021_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(default='\u6682\u65f6\u672a\u63a5\u53d7\u5230\u7b54\u6848'),
        ),
    ]
