# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhou', '0003_answer_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='quesion_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='zhou.Question'),
        ),
    ]
