# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhou', '0004_auto_20171022_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(default='\u8fd8\u6ca1\u6709\u63a5\u6536\u5230\u7b54\u6848,\u8bf7\u7a0d\u7b49'),
        ),
    ]
